apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopizer
  labels:
    app: shopizer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopizer
  template:
    metadata:
      labels:
        app: shopizer
    spec:
      containers:
      - name: shopizer
        image: kaushik0656m21/shopizer:v1
        ports:
        - containerPort: 8080

---

kind: Service
apiVersion: v1
metadata:
  name: shopizer-svc
spec:
  type: NodePort
  selector:
    app: shopizer
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30003
